version: 0.2
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yaml --output-template-file outputSamTemplate.yaml --s3-bucket umair-01
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
